vich_uploader:
  db_driver: orm

  mappings:
    profiles:
      uri_prefix: /images/profiles
      upload_destination: "%kernel.project_dir%/public/images/profiles"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: true
      delete_on_remove: true

    contacts:
      uri_prefix: /images/contacts
      upload_destination: "%kernel.project_dir%/public/images/contacts"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
      delete_on_update: true
      delete_on_remove: true
