version: "3.7"
services:
  database:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ypsi_cloud_rh_v5
    ports:
      - 44021:3306
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony_serveur
    restart: always
    depends_on:
      - database
    ports:
      - 44022:80
    environment:
      PMA_HOST: database
    networks:
      - dev

networks:
  dev:
